// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type relayRelayConfig struct {
	_          structs.HostLayout
	RelayIp    uint32
	TargetIp   uint32
	RelayPort  uint16
	TargetPort uint16
	RelayMac   [6]uint8
	NextHopMac [6]uint8
}

type relaySessionValue struct {
	_         structs.HostLayout
	ClientIp  uint32
	ClientMac [6]uint8
}

// loadRelay returns the embedded CollectionSpec for relay.
func loadRelay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RelayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load relay: %w", err)
	}

	return spec, err
}

// loadRelayObjects loads relay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*relayObjects
//	*relayPrograms
//	*relayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRelayObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRelay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// relaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relaySpecs struct {
	relayProgramSpecs
	relayMapSpecs
	relayVariableSpecs
}

// relayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayProgramSpecs struct {
	XdpRelayFunc *ebpf.ProgramSpec `ebpf:"xdp_relay_func"`
}

// relayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayMapSpecs struct {
	ConfigMap  *ebpf.MapSpec `ebpf:"config_map"`
	SessionMap *ebpf.MapSpec `ebpf:"session_map"`
}

// relayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayVariableSpecs struct {
}

// relayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayObjects struct {
	relayPrograms
	relayMaps
	relayVariables
}

func (o *relayObjects) Close() error {
	return _RelayClose(
		&o.relayPrograms,
		&o.relayMaps,
	)
}

// relayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayMaps struct {
	ConfigMap  *ebpf.Map `ebpf:"config_map"`
	SessionMap *ebpf.Map `ebpf:"session_map"`
}

func (m *relayMaps) Close() error {
	return _RelayClose(
		m.ConfigMap,
		m.SessionMap,
	)
}

// relayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayVariables struct {
}

// relayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayPrograms struct {
	XdpRelayFunc *ebpf.Program `ebpf:"xdp_relay_func"`
}

func (p *relayPrograms) Close() error {
	return _RelayClose(
		p.XdpRelayFunc,
	)
}

func _RelayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed relay_bpfeb.o
var _RelayBytes []byte
