// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type relayFwdKey struct {
	_           structs.HostLayout
	Vip         uint32
	ClientIp    uint32
	ServicePort uint16
	ClientPort  uint16
	Proto       uint8
	Pad1        uint8
	Pad2        uint16
}

type relayFwdVal struct {
	_          structs.HostLayout
	SnatIp     uint32
	TargetIp   uint32
	TargetPort uint16
	SnatPort   uint16
}

type relayRelayRule struct {
	_            structs.HostLayout
	RelayIp      uint32
	TargetIp     uint32
	TargetPort   uint16
	Pad          uint16
	RelayIfindex uint32
}

type relayRevKey struct {
	_          structs.HostLayout
	SnatIp     uint32
	TargetIp   uint32
	TargetPort uint16
	SnatPort   uint16
	Proto      uint8
	Pad1       uint8
	Pad2       uint16
}

type relayRevVal struct {
	_           structs.HostLayout
	ClientIp    uint32
	ClientPort  uint16
	ServicePort uint16
	Vip         uint32
}

// loadRelay returns the embedded CollectionSpec for relay.
func loadRelay() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RelayBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load relay: %w", err)
	}

	return spec, err
}

// loadRelayObjects loads relay and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*relayObjects
//	*relayPrograms
//	*relayMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRelayObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRelay()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// relaySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relaySpecs struct {
	relayProgramSpecs
	relayMapSpecs
	relayVariableSpecs
}

// relayProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayProgramSpecs struct {
	TcRelayFunc  *ebpf.ProgramSpec `ebpf:"tc_relay_func"`
	XdpRelayFunc *ebpf.ProgramSpec `ebpf:"xdp_relay_func"`
}

// relayMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayMapSpecs struct {
	ConfigMap *ebpf.MapSpec `ebpf:"config_map"`
	FwdMap    *ebpf.MapSpec `ebpf:"fwd_map"`
	RevMap    *ebpf.MapSpec `ebpf:"rev_map"`
}

// relayVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type relayVariableSpecs struct {
}

// relayObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayObjects struct {
	relayPrograms
	relayMaps
	relayVariables
}

func (o *relayObjects) Close() error {
	return _RelayClose(
		&o.relayPrograms,
		&o.relayMaps,
	)
}

// relayMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayMaps struct {
	ConfigMap *ebpf.Map `ebpf:"config_map"`
	FwdMap    *ebpf.Map `ebpf:"fwd_map"`
	RevMap    *ebpf.Map `ebpf:"rev_map"`
}

func (m *relayMaps) Close() error {
	return _RelayClose(
		m.ConfigMap,
		m.FwdMap,
		m.RevMap,
	)
}

// relayVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayVariables struct {
}

// relayPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRelayObjects or ebpf.CollectionSpec.LoadAndAssign.
type relayPrograms struct {
	TcRelayFunc  *ebpf.Program `ebpf:"tc_relay_func"`
	XdpRelayFunc *ebpf.Program `ebpf:"xdp_relay_func"`
}

func (p *relayPrograms) Close() error {
	return _RelayClose(
		p.TcRelayFunc,
		p.XdpRelayFunc,
	)
}

func _RelayClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed relay_bpfel.o
var _RelayBytes []byte
